### ISSUE TITLE
Why did I18N dumb terminal support break pexpect?

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#857]
**Describe the bug**
Since the following commit my test suite times out whilst using python-expect to interact with DOS.

$ git bisect bad
249b6486e83ee3e50816b5e3f92c4e8a41ca9920 is the first bad commit
commit 249b6486e83ee3e50816b5e3f92c4e8a41ca9920
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Tue Jun 11 01:34:24 2019 +0300

    kbd: I18N support for non-slang tty mode [#839]

:040000 040000 4970968ed62c797fc7838f82292caed8fb247f95 086a7d18c1d6743c1ebb8832aeb6960528cdb739 M	src

A description of what the problem is.
I no longer get any response to
~~~
child.expect([':\\>\r\n'], timeout=5)
child.send(version.bat\r\n')                                       
child.expect(['rem end\r\n'], timeout=5)
~~~
Where `version.bat` is a batch file containing `ver` and terminated with `rem end`. Timeout occurs on second expect, no output seen from `ver` 

**To Reproduce**
1/ Use python pexpect
2/ Spawn new dosemu process
3/ Do expect, send, expect

**Attach the binaries**
If the fix isn't immediately obvious to you, I can work on generating a very simple test case, otherwise I'm happy to test any possible fixes to help.
If the problem needs specific DOS files to reproduce, please attach.

**Comment by stsp** [comment]
Could you please just type `version.bat` by hands
and see what's going wrong?

**Comment by stsp** [comment]
`child.send(version.bat\r\n') `
Unpaired apostrophe?

**Comment by stsp** [comment]
Also I am not sure how `\r\n` is now
handled with that code. Try plain `\n`
or plain `\r`.

**Comment by stsp** [comment]
Also try to comment out `keyb_raw.c:90`, `(key == DKY_RETURN) ||`

**Comment by andrewbird** [comment]
> Unpaired apostrophe?

Only in my typing haste here :smile:

**Comment by andrewbird** [comment]
> Could you please just type version.bat by hands
and see what's going wrong?

Nothing appears wrong.

~~~
C:\>type version.bat
ver
rem end
~~~
~~~
C:\>version

C:\>ver

MS-DOS Version 6.22


C:\>rem end

C:\>
~~~

**Comment by andrewbird** [comment]
Also redirected the output to a file and typed `version` by hand.
~~~
000250 74 65 61 64 0d 0a 0d 0a 43 3a 5c 3e 0d 0a 43 3a  >tead....C:\>..C:<
000260 5c 3e 76 65 72 73 69 6f 6e 0d 0d 0a 0d 0a 43 3a  >\>version.....C:<
000270 5c 3e 76 65 72 0d 0a 0d 0a 4d 53 2d 44 4f 53 20  >\>ver....MS-DOS <
000280 56 65 72 73 69 6f 6e 20 36 2e 32 32 0d 0a 0d 0a  >Version 6.22....<
000290 0d 0a 43 3a 5c 3e 72 65 6d 20 65 6e 64 0d 0a 0d  >..C:\>rem end...<
0002a0 0a 43 3a 5c 3e 0d 0a 43 3a 5c 3e 65 78 69 74 65  >.C:\>..C:\>exite<
0002b0 6d 75 0d 0d 0a                                   >mu...<
0002b5
~~~

Received line endings are `\r\n` . I think the problem is in the transmit path.

**Comment by andrewbird** [comment]
> Also try to comment out `keyb_raw.c:90, (key == DKY_RETURN) ||`

Sorry, it didn't help.

**Comment by andrewbird** [comment]
I'll work on creating a standalone test case.

**Comment by andrewbird** [comment]
Here's the test case, extract in dev directory, run as `python ptest.py`

[pexpecttest.zip](https://github.com/stsp/dosemu2/files/3310216/pexpecttest.zip)

git checkout 249b6486e~1
~~~
$ python ptest.py 
C:\>version

C:\>ver

MS-DOS Version 6.22


C:\>
~~~





Current devel
~~~
$ python ptest.py 
Traceback (most recent call last):
  File "ptest.py", line 36, in <module>
    print runDosemu("version")
  File "ptest.py", line 25, in runDosemu
    child.expect(['rem end'], timeout=5)
  File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/dist-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python2.7/dist-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0xb73fd72c>
command: bin/dosemu.bin
args: ['bin/dosemu.bin', '-td', '-n', '-f', 'test-imagedir/dosemu.conf', '--Fimagedir', 'test-imagedir', '--Flibdir', 'test-libdir', '-o', 'ptest.log']
buffer (last 100 chars): '\nC:\\>'
before (last 100 chars): '\nC:\\>'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 2486
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <open file 'ptest.xpt', mode 'w' at 0xb73fb0d0>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("rem end")
~~~

**Comment by stsp** [comment]
Thanks, should now be fixed.

**Comment by andrewbird** [comment]
Thanks, test suite is working again now.
~~~
$ nosetests -v test/test_bootos.py:MSDOS622TestCase
Test MS-DOS-6.22 FAT12 image file ... ok
Test MS-DOS-6.22 FAT12 image file D writable ... ok
Test MS-DOS-6.22 FAT12 vfs directory ... ok
Test MS-DOS-6.22 FAT12 vfs directory boot.blk ... ok
Test MS-DOS-6.22 FAT16 image file ... ok
Test MS-DOS-6.22 FAT16 image file D writable ... ok
Test MS-DOS-6.22 FAT16 vfs directory ... ok
Test MS-DOS-6.22 FAT16 vfs directory boot.blk ... ok
Test MS-DOS-6.22 FAT16B image file ... ok
Test MS-DOS-6.22 FAT16B vfs directory ... ok
Test MS-DOS-6.22 FAT16B vfs directory boot.blk ... ok
Test MS-DOS-6.22 FAT32 disk info ... ok
Test MS-DOS-6.22 FAT DOSv2 delete file ... ok
Test MS-DOS-6.22 FAT DOSv2 delete file missing ... ok
Test MS-DOS-6.22 FAT DOSv2 rename dir ... ok
Test MS-DOS-6.22 FAT DOSv2 rename dir src missing ... ok
Test MS-DOS-6.22 FAT DOSv2 rename dir tgt exists ... ok
Test MS-DOS-6.22 FAT DOSv2 rename file ... ok
Test MS-DOS-6.22 FAT DOSv2 rename file src missing ... ok
Test MS-DOS-6.22 FAT DOSv2 rename file tgt exists ... ok
Test MS-DOS-6.22 FAT FCB file rename simple ... ok
Test MS-DOS-6.22 FAT FCB file rename source missing ... ok
Test MS-DOS-6.22 FAT FCB file rename target exists ... ok
Test MS-DOS-6.22 FAT FCB file rename wildcard one ... ok
Test MS-DOS-6.22 FAT FCB file rename wildcard two ... ok
Test MS-DOS-6.22 FAT FCB file rename wildcard three ... ok
Test MS-DOS-6.22 FAT FCB file rename wildcard four ... ok
Test MS-DOS-6.22 FAT AUTO vfs directory ... ok
Test MS-DOS-6.22 Floppy image file ... ok
Test MS-DOS-6.22 Floppy vfs directory ... ok
Test MS-DOS-6.22 INT21 disk info ... ok
Test MS-DOS-6.22 LFN volume info on FAT(img) ... ok
Test MS-DOS-6.22 LFN volume info on MFS ... ok
Test MS-DOS-6.22 MFS auto hd vfs directory redirection ... ok
Test MS-DOS-6.22 MFS DOSv2 delete file ... ok
Test MS-DOS-6.22 MFS DOSv2 delete file missing ... ok
Test MS-DOS-6.22 MFS DOSv2 rename dir ... ok
Test MS-DOS-6.22 MFS DOSv2 rename dir src missing ... ok
Test MS-DOS-6.22 MFS DOSv2 rename dir tgt exists ... ok
Test MS-DOS-6.22 MFS DOSv2 rename file ... ok
Test MS-DOS-6.22 MFS DOSv2 rename file src missing ... ok
Test MS-DOS-6.22 MFS DOSv2 rename file tgt exists ... ok
Test MS-DOS-6.22 MFS FCB file rename simple ... ok
Test MS-DOS-6.22 MFS FCB file rename source missing ... ok
Test MS-DOS-6.22 MFS FCB file rename target exists ... ok
Test MS-DOS-6.22 MFS FCB file rename wildcard one ... ok
Test MS-DOS-6.22 MFS FCB file rename wildcard two ... ok
Test MS-DOS-6.22 MFS FCB file rename wildcard three ... ok
Test MS-DOS-6.22 MFS FCB file rename wildcard four ... ok
Test MS-DOS-6.22 MFS LFN directory change current ... ok
Test MS-DOS-6.22 MFS LFN directory create ... ok
Test MS-DOS-6.22 MFS LFN directory delete ... ok
Test MS-DOS-6.22 MFS LFN directory delete not empty ... ok
Test MS-DOS-6.22 MFS LFN file append ... ok
Test MS-DOS-6.22 MFS LFN file create ... ok
Test MS-DOS-6.22 MFS LFN file create readonly ... ok
Test MS-DOS-6.22 MFS LFN file find ... ok
Test MS-DOS-6.22 MFS LFN file read ... ok
Test MS-DOS-6.22 MFS LFN file truncate ... ok
Test MS-DOS-6.22 MFS LFN get current directory ... ok
Test MS-DOS-6.22 MFS LFN Truename ... ok
Test MS-DOS-6.22 MFS lredir2 command redirection ... ok
Test MS-DOS-6.22 MFS SFN directory change current ... ok
Test MS-DOS-6.22 MFS SFN directory create ... ok
Test MS-DOS-6.22 MFS SFN directory delete ... ok
Test MS-DOS-6.22 MFS SFN directory delete not empty ... ok
Test MS-DOS-6.22 MFS SFN file append ... ok
Test MS-DOS-6.22 MFS SFN file create ... ok
Test MS-DOS-6.22 MFS SFN file create readonly ... ok
Test MS-DOS-6.22 MFS SFN file find ... ok
Test MS-DOS-6.22 MFS SFN file read ... ok
Test MS-DOS-6.22 MFS SFN file truncate ... ok
Test MS-DOS-6.22 MFS SFN get current directory ... ok
Test MS-DOS-6.22 MFS SFN Truename ... ok
Test MS-DOS-6.22 SysType ... ok
Test MS-DOS-6.22 Three vfs directories configured ... ok

----------------------------------------------------------------------
Ran 76 tests in 350.251s

OK
~~~

Will run same test on FDPP later!
